export enum API {
  CLOUD = "cloud",
  DASHBOARD = "dashboard",
  DASHBOARDS = "dashboards",
  IMAGES = "images",
  MESSAGES = "messages",
  PREFERENCE = "preference",
  PREFERENCES = "preferences",
  PRESENTATION = "presentation",
  PRESENTATIONS = "presentations",
  SERIES = "series",
  SLIDE = "slide",
  SLIDES = "slides",
  TOPICS = "topics",
  WIDGET = "widget",
  WIDGETS = "widgets",
}
