export enum CSS {
  API = 'color:white;background-color:grey;padding:0 4px 0 4px;border-radius:5px;',
  APP = 'color:white;background-color:navy;padding:0 4px 0 4px;border-radius:5px;',
  BROADCAST = 'color:navy;background-color:orange;padding:0 4px 0 4px;border-radius:5px;',
  CLOUD = 'color:purple;background-color:mistyrose;padding:0 4px 0 4px;border-radius:5px;',
  DATA = 'color:grey;background-color:lightskyblue;padding:0 4px 0 4px;border-radius:5px;',
  ERROR = 'color:white;background-color:red;padding:0 4px 0 4px;border-radius:5px;',
  GET_DATA = 'color:black;background-color:lime;padding:0 4px 0 4px;border-radius:5px;',
  HIDE = 'color:white;background-color:red;padding:0 4px 0 4px;border-radius:5px;',
  KO = 'color:white;background-color:red;padding:0 4px 0 4px;border-radius:5px;',
  MESSAGES = 'color:white;background-color:darkslateblue;padding:0 4px 0 4px;border-radius:5px;',
  NO_UPDATES = 'color:grey;border:1px solid grey;padding:0 4px 0 4px;border-radius:5px;',
  NONE = 'color:transparent;background-color:transparent;',
  OK = 'color:black;background-color:lime;padding:0 4px 0 4px;border-radius:5px;',
  PRESENTATION = 'color:white;background-color:darkred;padding:0 4px 0 4px;border-radius:5px;',
  SERIES = 'color:purple;background-color:thistle;padding:0 4px 0 4px;border-radius:5px;',
  SLIDE = 'color:black;background-color:yellow;padding:0 4px 0 4px;border-radius:5px;',
  STORAGE = 'color:black;background-color:cyan;padding:0 4px 0 4px;border-radius:5px;',
  SUBSCRIBE = 'color:white;background-color:dodgerblue;padding:0 4px 0 4px;border-radius:5px;',
  WIDGET = 'color:gret;background-color:lemonchiffon;padding:0 4px 0 4px;border-radius:5px;',
  WS = 'color:white;background-color:green;padding:0 4px 0 4px;border-radius:5px;',
}